language: node_js
sudo: false
node_js:
  - stable
  - lts/dubnium

env:
  global:
    - COVERALLS_PARALLEL=true

os:
  - linux
  - osx

cache:
  directories:
    - node_modules
before_cache: rm -rf node_modules/.cache
install: npm install --build-from-source
after_success: cat ./coverage/lcov.info | coveralls

notifications:
  webhooks: https://coveralls.io/webhook
